config/routes.rb
Rails.application.routes.draw do

  post 'suggestions/random'
  get 'suggestions/filter'
  get 'suggestions/provider_suggestions/new', to: 'suggestions#new_provider_suggestion'
  get 'suggestions/posts/new', to: 'suggestions#new_post'
  get 'signup', to: 'users#new'

  resources :suggestions, only: [:create, :show]
  resources :users

  root 'suggestions#filter'

end

app/models/category_range.rb
class CategoryRange < ActiveRecord::Base
end

app/models/crowd_range.rb
class CrowdRange < ActiveRecord::Base
end

app/models/duration_range.rb
class DurationRange < ActiveRecord::Base
end

app/models/money_range.rb
class MoneyRange < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :suggestion
end

app/models/provider.rb
class Provider < ActiveRecord::Base
end

app/models/provider_suggestion.rb
class ProviderSuggestion < ActiveRecord::Base
end

app/models/site_range.rb
class SiteRange < ActiveRecord::Base
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  has_many :posts
  has_many :provider_suggestions
  belongs_to :crowd_range
  belongs_to :category_range
  belongs_to :duration_range
  belongs_to :money_range
  belongs_to :site_range
  accepts_nested_attributes_for :posts, :provider_suggestions, reject_if: :all_blank
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            length: { maximum: 255 },
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_paramz)
    if post.save
      redirect_to controller: 'suggestions', action: :show, id: post.suggestion_id
    else
      render :new
    end
  end

  private

  def post_paramz
    params.require(:post).permit(:title, :body, {suggestion: [:title]})
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  def filter
    @suggestion_filter = SuggestionFilter.new
  end

  def random
    @suggestion_filter = SuggestionFilter.new(suggestion_filter_params)

    suggestions = Suggestion.where({duration_range_id: @suggestion_filter.duration,
                                    crowd_range_id: @suggestion_filter.crowd,
                                    category_range_id: @suggestion_filter.category,
                                    site_range_id: @suggestion_filter.site,
                                    money_range_id: @suggestion_filter.money}.delete_if {|k,v| v.empty? })

    if suggestions.empty?
      flash[:state] = 'try one more time!'
      redirect_to suggestions_filter_path

    else
      @suggestion = suggestions[Random.rand(suggestions.size)]
    end
  end

  def show
    @suggestion = Suggestion.find(params[:id])
  end

  def new_post
    @suggestion = Suggestion.new
    @suggestion.posts=[Post.new]
    render :new
  end

  def new_provider_suggestion
    @suggestion = Suggestion.new
    @suggestion.provider_suggestions=[ProviderSuggestion.new]
    render :new
  end

  def create
    @suggestion = Suggestion.new(suggestion_params)
    if @suggestion.save
      redirect_to @suggestion
    else
    #   should do something! todo
    end
  end

  private

  def suggestion_params
    params.require(:suggestion).permit(:title, :description, :category_range_id, :crowd_range_id,
                                       :site_range_id, :duration_range_id, :money_range_id,
                                       posts_attributes: [:title, :body],
                                       provider_suggestions_attributes: [:title, :description])
  end

  def suggestion_filter_params
    params.require(:suggestion_filter).permit(:duration, :category, :crowd, :site, :money)
  end

end

class SuggestionFilter
  include ActiveModel::Model
  attr_accessor :duration, :category, :crowd, :site, :money

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Watodo</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<div id="main-container" class="container">
    <div class="row">
        <div class="col-xs-3">
            <h3><%= link_to 'Watado', suggestions_filter_path %></h3>
            <h5><%= link_to 'New post', suggestions_posts_new_path %></h5>
            <h5><%= link_to 'New provider suggestion', suggestions_provider_suggestions_new_path %></h5>
            <h5><%= link_to 'Sign up', signup_path %></h5>
        </div>
        <div class="col-xs-9">
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
        </div>
        <%= debug(params) if Rails.env.development? %>
    </div>
</div>

</body>
</html>

app/views/posts/_post.html.erb
<%= form_for @post do |f| %>
    <div class="field form-group">
      <%= f.label :title, class: 'control-label' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="field form-group">
      <%= f.label :body, class: 'control-label' %>
      <%= f.text_area :body, class: 'form-control' %>
    </div>

    <%= f.fields_for :suggestion do |suggestion_form| %>
        <%=suggestion_form.label 'Suggestion title', class: 'control-label' %>
        <%= suggestion_form.text_field :title, class: 'form-control' %>
    <%end %>

    <div class="actions form-group">
      <%= f.submit 'Go' %>
    </div>
<% end %>

app/views/posts/new.html.erb
<%=render 'post' %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/suggestions/_filter.html.erb
<%= form_for @suggestion_filter, url: suggestions_random_path, html: {class: 'form-inline'} do |f| %>
    <% if @suggestion_filter.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@suggestion_filter.errors.count, "error") %> prohibited this suggestion filter from being saved:</h2>

          <ul>
            <% @suggestion_filter.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :crowd, class: 'control-label' %>
      <%= f.select :crowd, CrowdRange.all.map{|range| [range.name, range.id]}, class: 'form-control', include_blank: true %>
    </div>

    <div class="field form-group">
      <%= f.label :duration, class: 'control-label' %>
      <%= f.select :duration, DurationRange.all.map{|range| [range.name, range.id]}, class: 'form-control', include_blank: true %>
    </div>

    <div class="field form-group">
      <%= f.label :category, class: 'control-label' %>
      <%= f.select :category, CategoryRange.all.map{|range| [range.name, range.id]}, class: 'form-control', include_blank: true %>
    </div>

    <div class="field form-group">
      <%= f.label :site, class: 'control-label' %>
      <%= f.select :site, SiteRange.all.map{|range| [range.name, range.id]}, class: 'form-control', include_blank: true %>
    </div>

    <div class="field form-group">
      <%= f.label :money, class: 'control-label' %>
      <%= f.select :money, MoneyRange.all.map{|range| [range.name, range.id]}, class: 'form-control', include_blank: true %>
    </div>

    <div class="actions form-group">
      <%= f.submit 'Go' %>
    </div>

<% end %>

app/views/suggestions/_suggestion.html.erb
<h1><%= content_tag :div, @suggestion.title %></h1>
<h1><%= content_tag :div, @suggestion.description %></h1>

<div>
  <h2>Filters</h2>
<% @suggestion.attributes.each do |k, v| %>
    <% if( k && k.to_s.include?('range') && !v.nil?) %>
        <%= content_tag :p, @suggestion.send(k[/.*range/]).name %>
    <%end%>
<%end%>
</div>
<% @suggestion.posts.each do |post| %>
    <div>
      <%= content_tag :h2, post.title %>
      <%= content_tag :p, post.body %>
    </div>
<% end %>
<% @suggestion.provider_suggestions.each do |provider_suggestion| %>
    <div>
      <%= content_tag :h2, provider_suggestion.title %>
      <%= content_tag :p, provider_suggestion.description %>
    </div>
<% end %>

app/views/suggestions/filter.html.erb
<%= render 'filter' %>
<%= content_tag :div, flash[:state] %>

app/views/suggestions/new.html.erb
<%= form_for @suggestion do |f| %>
    <div>
      <%= f.fields_for :posts do |post_form| %>
          <%=post_form.label 'Post title', class: 'control-label' %>
          <%= post_form.text_field :title, class: 'form-control' %>

          <%=post_form.label 'Post body', class: 'control-label' %>
          <%= post_form.text_area :body, class: 'form-control' %>
      <%end %>

      <%= f.fields_for :provider_suggestions do |provider_suggestion_form| %>
          <%=provider_suggestion_form.label 'Provider suggestion', class: 'control-label' %>
          <%= provider_suggestion_form.text_field :title, class: 'form-control' %>

          <%=provider_suggestion_form.label 'Provider suggestion description', class: 'control-label' %>
          <%= provider_suggestion_form.text_area :description, class: 'form-control' %>
      <%end %>
    </div>


    <div>
      <div class="field form-group">
        <%= f.label :title, class: 'control-label' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :description, class: 'control-label' %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :crowd_range, class: 'control-label' %>
        <%= f.select :crowd_range_id, CrowdRange.all.map{|range| [range.name, range.id]}, class: 'form-control', include_blank: true %>
      </div>

      <div class="field form-group">
        <%= f.label :duration_range, class: 'control-label' %>
        <%= f.select :duration_range_id, DurationRange.all.map{|range| [range.name, range.id]}, class: 'form-control', include_blank: true %>
      </div>

      <div class="field form-group">
        <%= f.label :category_range, class: 'control-label' %>
        <%= f.select :category_range_id, CategoryRange.all.map{|range| [range.name, range.id]}, class: 'form-control', include_blank: true %>
      </div>

      <div class="field form-group">
        <%= f.label :site_range, class: 'control-label' %>
        <%= f.select :site_range_id, SiteRange.all.map{|range| [range.name, range.id]}, class: 'form-control', include_blank: true %>
      </div>

      <div class="field form-group">
        <%= f.label :money_range, class: 'control-label' %>
        <%= f.select :money_range_id, MoneyRange.all.map{|range| [range.name, range.id]}, class: 'form-control', include_blank: true %>
      </div>

    </div>

    <div class="actions form-group">
      <%= f.submit 'Go' %>
    </div>
<% end %>

app/views/suggestions/random.html.erb
<%= render 'filter' %>
<%= render @suggestion %>

app/views/suggestions/show.html.erb
<%= render @suggestion %>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-lock"></span> Sign up</div>
                <div class="panel-body">
                    <%= form_for @user, html: {class: "form-horizontal"} do |f| %>
                        <%= render 'shared/error_messages' %>
                        <div class="form-group">
                                <%= f.label :name, class: "col-sm-3 control-label" %>
                            <div class="col-sm-9">
                                <%= f.text_field :name, class: "form-control" %>
                            </div>
                        </div>

                        <div class="form-group">
                                <%= f.label :email, class: "col-sm-3 control-label" %>
                            <div class="col-sm-9">
                                <%= f.text_field :email, class: "form-control" %>
                            </div>
                        </div>

                        <div class="form-group">
                            <%= f.label :password, class: "col-sm-3 control-label" %>
                            <div class="col-sm-9">
                                <%= f.password_field :password, class: "form-control" %>
                            </div>
                        </div>

                        <div class="form-group">
                            <%= f.label :password_confirmation, "Confirmation", class: "col-sm-3 control-label" %>
                            <div class="col-sm-9">
                                <%= f.password_field :password_confirmation, class: "form-control" %>
                            </div>
                        </div>

                        <div class="form-group last">
                            <div class="col-sm-offset-3 col-sm-6">
                                <%= f.submit "Create my account", class: "btn btn-primary" %>
                            </div>
                        </div>

                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>
<% provide(:title, @user.name) %>
<h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
</h1>